MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path
from MeuApp import views
from django.urls.conf import include
urlpatterns = [
    path('',views.home, name='inicio'),
    path('about',views.about,name='about'),
    path('admin/', admin.site.urls), #remover pois se nao podem atacar o site, da acesso a parte de adminstrador
    path("contatos/", include ('contatos.urls'))
]

MeuSite/contatos/urls.py
from django.urls.conf import path
from contatos import views
app_name = "contatos"
urlpatterns = [
    path('cria/', views.ContatoCreateView.as_view(),
    name='cria-contato'),
    path('lista/', views.ContatoListView.as_view(),
    name='lista-contatos'),
    path('', views.ContatoListView.as_view(),
    name='home-contatos'),
    path('atualiza/<int:pk>/',
    views.ContatoUpdateView.as_view(),
    name='atualiza-contato'),
    path('apaga/<int:pk>/',
    views.ContatoDeleteView.as_view(),
    name='apaga-contato'),
]

MeuSite/MeuApp/models.py
from django.db import models

# Create your models here.

MeuSite/contatos/models.py
from django.db import models

class Pessoa(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(
    max_length=100, help_text='Entre o nome')
    idade = models.IntegerField(help_text='Entre a idade')
    salario = models.DecimalField(
    help_text='Entre o salário',
    decimal_places=2, max_digits=8)
    email = models.EmailField(
    help_text='Informe o email', max_length=254)
    telefone = models.CharField(
    help_text='Telefone com DDD e DDI', max_length=20)
    dtNasc = models.DateField(
    help_text='Nascimento no formato DD/MM/AAAA',
    verbose_name='Data de nascimento')
    def __str__(self):
        return self.nome

MeuSite/contatos/forms.py
from django import forms
from contatos.models import Pessoa

class ContatoModel2Form(forms.ModelForm):
    dtNasc = forms.DateField(
    input_formats=['%d/%m/%Y'],
    label='Data do nascimento',
    help_text='Nascimento no formato DD/MM/AAAA',
    )
    class Meta:
        model = Pessoa
        fields = '__all__'

MeuSite/MeuApp/views.py
from django.shortcuts import render
#from django.http import HttpResponse
# Create your views here.
def home(request):
    #return HttpResponse("Olá mundo", content_type="text/plain")
    return render(request, 'MeuApp/home.html')
def about(request):
    # processamento antes de mostrar a segunda página
    return render(request, 'MeuApp/about.html')

MeuSite/contatos/views.py
from django.shortcuts import get_object_or_404, render
from contatos.models import Pessoa
from django.views.generic.base import View
from contatos.forms import ContatoModel2Form
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
class ContatoListView(View):
    def get(self, request, *args, **kwargs):
        pessoas = Pessoa.objects.all()
        contexto = { 'pessoas': pessoas, }
        return render(
        request,
        'contatos/listaContatos.html',
        contexto)
class ContatoCreateView(View):
    def get(self, request, *args, **kwargs):
        contexto = { 'formulario':ContatoModel2Form, }
        return render(request,
        "contatos/criaContato.html", contexto)
    def post(self, request, *args, **kwargs):
        formulario = ContatoModel2Form(request.POST)
        if formulario.is_valid():
            contato = formulario.save() 
            contato.save()
        return HttpResponseRedirect(reverse_lazy(
            "contatos:lista-contatos"))
class ContatoUpdateView(View):
    def get(self, request, pk, *args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        formulario = ContatoModel2Form(instance=pessoa)
        context = {'pessoa': formulario, }
        return render(request, 'contatos/atualizaContato.html', context)
    def post(self, request, pk, *args, **kwargs):
        pessoa = get_object_or_404(Pessoa, pk=pk)
        formulario = ContatoModel2Form(request.POST, instance=pessoa)
        if formulario.is_valid():
            pessoa = formulario.save() # cria uma pessoa com os dados do formulário
            pessoa.save() # salva uma pessoa no banco de dados
            return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))
        else:
            contexto = {'pessoa': formulario, }
            return render(request, 'contatos/atualizaContato.html', contexto)
class ContatoDeleteView(View):
    def get(self, request, pk, *args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        contexto = { 'pessoa': pessoa}
        return render(request, 'contatos/apagaContato.html',contexto)

    def post(self, request, pk, *args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        pessoa.delete()
        return HttpResponseRedirect(
        reverse_lazy("contatos:lista-contatos"))

MeuSite/MeuApp/templates/MeuApp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Segunda pagina</h1>
    <div>Volta para <a href="{% url 'inicio' %}">Inicio</a></div>
</body>
</html>

MeuSite/MeuApp/templates/MeuApp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Home page Do meu projeto exemplos</h1>
    <ul> 
        <li> <a href="{% url 'contatos:lista-contatos' %}">Contatos</a></li>  <!--Informar que acha na pasta contatos.-->
    </ul>
</body>
</html>

MeuSite/contatos/templates/contatos/apagaContato.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Apaga Contato</title>
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Remoção de contatos</h1>
    <form method="POST">
    {% csrf_token %}
    Confirma a remoção de {{ pessoa }}?<br>
    <button>
    <a href="{% url 'contatos:lista-contatos' %}"
    style="text-decoration: none; color: black;">Cancela</a>
    </button>
    <input type="submit" value="Remove">
</form>
</body>
</html>

MeuSite/contatos/templates/contatos/atualizaContato.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Atualiza Contato</title>
<link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Atualização de contatos</h1>
    <form method="POST" class='formulario'>
        {% csrf_token %}
    <table>
        {{ pessoa.as_table }}
    <tr>
    <td></td>
    <td><input type="submit" value="Atualiza"></td>
    </tr>
</table>
</form>
</body>
</html>

MeuSite/contatos/templates/contatos/criaContato.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
     <title>Cria Contato</title>
    <link rel="stylesheet"
        href="{% static 'contatos/css/estilo.css' %}">
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Cria um contato</h1>
    <form action="" method="POST">
        <fieldset style="width: max-content;">
            <legend>Formulário de Cadastro</legend>
            {% csrf_token %}
            <table class='formulario'>
                {{formulario.as_table}}
            </table>
            <button type="submit">Cria contato</button>
        </fieldset>
    </form>
</body>

MeuSite/contatos/templates/contatos/links.html
<!--
Para incluir esse fragmento de página HTML
em uma página HTML use:
{ % include 'contatos/links.html' % }
-->
<div>
    <a href="/">
        Home-Page
        </a> |
        <a href="{% url 'contatos:home-contatos' %}">
        Página inicial
        </a> |
        <a href="{% url 'contatos:lista-contatos' %}">
        Listar contatos
        </a> |
        <a href="{% url 'contatos:cria-contato' %}">
        Cadastrar contato
    </a>
        <hr>
</div>

MeuSite/contatos/templates/contatos/listaContatos.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Lista Contatos</title>
<link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Lista de Contatos</h1>
    <table>
        <tr><th>Nome</th><th>Idade</th><th>Salário</th><th>Ações disponíveis</th></tr>  
        {% for pessoa in pessoas %}
            <tr>
                <td>{{ pessoa.nome }}</td><td>{{pessoa.idade }}</td><td>{{ pessoa.salario }}</td>
                <td><a href="{% url 'contatos:atualiza-contato' pk=pessoa.id %}">Atualizar</a> |
                    <a href="{% url 'contatos:apaga-contato' pk=pessoa.id %}">Excluir</a></td>
            </tr>
        {% empty %}
            <tr><th colspan="5">Ainda não tem contatos cadastrados</th></tr>
        {% endfor %}
    </table>
</body>
</html>